%%
clear
close all
IAD='ITD';
TaskFormat='3I-3AFC';
TaskFormat='2I-2AFC';
TranspositionFreq = 4000;
%TranspositionFreq = 0;
ModulationRate = 500;
ModulationRate = 125;
VolumeSettingsFile='VolumeSettings4kHzILD.txt';
VolumeSettingsFile='VolumeSettings500HzILD.txt';

if strcmp(IAD, 'ITD')
    ITD = 650; % in us -- 12500 is 1/2 period for 40 Hz modulation
    starting_SNR=20*log10(ITD/100);
    START_change_dB=6;
    MIN_change_dB = 1;
else
    starting_SNR=3;
    MIN_change_dB = 0.25;
    START_change_dB=1;
    MIN_SNR_dB=0.25; % minimal difference: for ILD only
    % Remember, it's twice this!
    InitialDescentMinimum=.5;
end

if strcmp(TaskFormat,'2I-2AFC')
    TransposedIADs('SR', 'starting_SNR',starting_SNR, ...
        'TranspositionFreq', TranspositionFreq, ...
        'ModulationRate', ModulationRate, ...
        'TaskFormat', TaskFormat, ...
        'MaximalDifference', 1, 'IAD', IAD, ...
        'START_change_dB', START_change_dB, 'MIN_change_dB', MIN_change_dB, ...
        'usePlayrec', 1, 'RMEslider', 'TRUE', ...
        'trackAbsThreshold', 0, 'GoButton', 1, ...
        'preSilence', 200, ...
        'ModulationPhase', 0, ...
        'VolumeSettingsFile', VolumeSettingsFile, 'LongMaskerNoise', 1500,...
        'PlotTrackFile', 1, 'outputAllWavs', 1, 'DEBUG', 0);
    % ,...
    % 'BackNzLevel', -100, ...
    %    'ModulationPhase', -3*pi/2, ...
    %     'ToneDuration', 500, 'WithinPulseISI', 100, 'NoiseDuration', 500, ...
    %     'LongMaskerNoise', 00, 'fixed', 'signal');
else
    TransposedIADs('SR', 'starting_SNR',starting_SNR, ...
        'ModulationRate', 125, ...
        'TaskFormat', TaskFormat, ...
        'MaximalDifference', 1, 'IAD', IAD, ...
        'START_change_dB', START_change_dB, 'MIN_change_dB', MIN_change_dB, ...
        'usePlayrec', 0, 'RMEslider', 'FALSE', ...
        'trackAbsThreshold', 0, 'GoButton', 1, ...
        'TranspositionFreq', 4000, ...
        'ModulationPhase', 0, ...
        'VolumeSettingsFile', 'VolumeSettings4kHzILD.txt', 'LongMaskerNoise', 3000,...
        'PlotTrackFile', 1, 'outputAllWavs', 1, 'DEBUG', 0);
    % ,...
    %         'BackNzLevel', -100, ...
    %    'ModulationPhase', -3*pi/2, ...
    %     'ToneDuration', 500, 'WithinPulseISI', 100, 'NoiseDuration', 500, ...
    %     'LongMaskerNoise', 00, 'fixed', 'signal');
end

return
SNR=-2
100*10^(SNR/20)

